fix workflow II

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,7 +17,7 @@ jobs:
         run: |
           BRANCH="$(echo $GITHUB_REF | sed 's|refs/heads/||')"
           echo "BRANCH=$BRANCH" >> $GITHUB_ENV
-          echo "INSTALL_CMD=npm install --legacy-peer-deps --omit=dev" >> $GITHUB_ENV
+          echo "INSTALL_CMD=npm install --omit=dev" >> $GITHUB_ENV
 
           if [ "$BRANCH" = "main" ]; then
             echo "PORT=4009" >> $GITHUB_ENV
@@ -56,7 +56,7 @@ jobs:
 
       - name: Install dependencies
         run: |
-          sudo -u www bash -c "cd '$DEPLOY_PATH' && $INSTALL_CMD && npm audit fix --legacy-peer-deps" || { echo "npm install failed"; exit 1; }
+          sudo -u www bash -c "cd '$DEPLOY_PATH' && $INSTALL_CMD && npm audit fix" || { echo "npm install failed"; exit 1; }
 
       - name: Remove .next cache
         run: |
